name = "rn-lottery-web"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
# 如果你有自定义域名，在这里配置
# routes = [
#   { pattern = "lottery.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Pages配置
[env.production.vars]
NODE_ENV = "production"

# 重定向规则（用于SPA路由）
[[env.production.rules]]
action = "rewrite"
expression = "http.request.uri.path matches \"^/(?!api/|static/|_).*$\" and not http.request.uri.path matches \"\\.[a-zA-Z0-9]+$\""
value = "/index.html"
